spring.application.name=smartgarage
# Server port
server.port=8080

# C?u hình PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/smart_garage
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA / Hibernate cho Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# T? ??ng chuy?n CamelCase (Java) sang Snake_case (Postgres)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
local-ai.base-url=${LOCAL_AI_BASE_URL:http://localhost:11434}
local-ai.model=${LOCAL_AI_MODEL:qwen2.5:7b}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=6351071051@st.utc2.edu.vn
spring.mail.password=djlk majm dmyv sqcv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads

ors.enabled=${ORS_ENABLED:true}
ors.base-url=${ORS_BASE_URL:https://api.openrouteservice.org}
ors.api-key=${ORS_API_KEY:eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjllMDg5Y2FiYWI2NTQ0ZDI4YmMyZWRjZWRlNGU0OTVjIiwiaCI6Im11cm11cjY0In0=}
ors.profile=${ORS_PROFILE:driving-car}
