ALTER TABLE chat_rooms
    ADD COLUMN IF NOT EXISTS hidden_for_customer BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS hidden_for_admin BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS hidden_for_superadmin BOOLEAN NOT NULL DEFAULT FALSE;
